### ISSUE TITLE
Neovim: KeyboardInterrupt

### ISSUE THREAD

**Issue by rstacruz** [SirVer/ultisnips#763]
This frequently happens to me:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 46, in ensure
    if self._needs_update(ft):
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 62, in _needs_update
    existing_files = self._get_all_snippet_files_for(ft)
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet/source/file/ultisnips.py", line 183, in _get_all_snippet_files_for
    return find_all_snippet_files(ft)
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/snippet/source/file/ultisnips.py", line 35, in find_all_snippet_files
    snippet_dirs = _vim.eval('g:UltiSnipsSnippetDirectories')
  File "/Users/rsc/.vim/vendor/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/script_host.py", line 187, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Keyboard interrupt'
```

**Comment by seletskiy** [comment]
@rstacruz: I do not use neovim personally, so everything I can help you with is either consider switching to vanilla vim or investigating issue by yourself. I will gladly assist you in that case.

**Comment by joebalancio** [comment]
@rstacruz I get this too when I use `ctrl-c` as an alternative to `esc`. Try using `ctrl-[` or [map `esc` to something else](http://vim.wikia.com/wiki/Avoid_the_escape_key)

**Comment by rstacruz** [comment]
Ah yes, this seems indeed more like a problem with Neovim configuration. [Here's](http://ricostacruz.com/til/neovim-with-python-on-osx) how I fixed it on OSX.

**Comment by chrisnicola** [comment]
Updating pip does not seem to fix this problem.

Might be worth noting the YouCompleteMe recently had to address this problem.

https://github.com/Valloric/YouCompleteMe/issues/2289

**Comment by chrisnicola** [comment]
As a stopgap solution I've found adding this to `err_to_scratch_buffer.py` works for now. Probably not ideal, but it is unusable with the error messages popping up nearly every time I hit `ctrl-C` to return to normal mode.

```
    def wrapper(self, *args, **kwds):
        try:
            return func(self, *args, **kwds)
        except NvimError:
            return
        except Exception as e:  # pylint: disable=bare-except
            msg = \
```

**Comment by ppiet** [comment]
I hit this regularly (on Linux) with fresh pip packages and nvim 1.6.

**Comment by wookayin** [comment]
@rstacruz's solution does not fix the problem. I have both of `g:python_host_prog` and `g:python3_host_prog` configured in `init.vim`.

**Comment by joebalancio** [comment]
@chrisnicola @ppiet @wookayin I noticed the other day that neovim was bumped to [0.1.7](https://github.com/neovim/neovim/releases/tag/v0.1.7). Part of that release is this PR https://github.com/neovim/neovim/pull/5546 which might address this issue although I haven't tested that theory out.

Personally, I recently started avoiding `ctrl-c` entirely because of this and have been very happy since.

**Comment by rstacruz** [comment]
Still happening in 0.1.7 by the way! The best solution at the moment is to avoid ctrl-c :\

**Comment by wookayin** [comment]
I think this issue needs to be re-opened.

**Comment by ppiet** [comment]
Still happening in 0.2.0. @rstacruz wdyt about re-opening the issue?

**Comment by danijar** [comment]
Seems like this is still an issue:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
    return func(self, *args, **kwds)
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 205, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 679, in _snips
    source.ensure(filetypes)
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 32, in ensure
    self._load_snippets_for(ft)
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    for fn in self._get_all_snippet_files_for(ft):
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/snipmate.py", line 125, in _get_all_snippet_files_for
    return _snipmate_files_for(ft)
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/snipmate.py", line 46, in _snipmate_files_for
    for rtp in vim_helper.eval("&runtimepath").split(","):
  File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/vim_helper.py", line 123, in eval
    return vim.eval(text)
  File "/usr/lib/python3/dist-packages/pynvim/plugin/script_host.py", line 209, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Keyboard interrupt
```
