### ISSUE TITLE
Error detected while processing function UltiSnips#TrackChange when hitting a function key in insert mode

### ISSUE THREAD

**Issue by mgedmin** [SirVer/ultisnips#819]
Every time I hit an unmapped function key in insert mode, I get this:

```
Error detected while processing function UltiSnips#TrackChange:                                                                             
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/mg/.vim/bundle/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
    return func(self, *args, **kwds)
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/mg/.vim/bundle/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 838, in _track_change
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
    inserted_char = _vim.eval('v:char')
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/mg/.vim/bundle/UltiSnips/pythonx/UltiSnips/_vim.py", line 121, in eval
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
    rv = vim.eval(as_vimencoding(text))
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
During handling of the above exception, another exception occurred:
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/mg/.vim/bundle/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 50, in wrapper
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
    _vim.new_scratch_buffer(msg)
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/mg/.vim/bundle/UltiSnips/pythonx/UltiSnips/_vim.py", line 157, in new_scratch_buffer
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
    vim.command('botright new')
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
vim.error: Vim(new):E523: Not allowed here: botright new
Press ENTER or type command to continue
```

I'm using Vim 8.0.311 built with Python 3 support.

**Comment by mgedmin** [comment]
I should've git pulled before filing the bug -- this is fixed in 5352d98f212e273b3e8b1d84efdbe2d6a6d557e9.

**Comment by hoetmaaiers** [comment]
I still have this issue and have ran 'PluginUpdate' (Vundle). How should I fix this?
The error started when I updated Vim from native MacOS to Homebrew based version (8.0).

**Comment by ttcremers** [comment]
@hoetmaaiers are you sure you're using the vim from your Cellar directory? I just solved this issue by installing the brew version of vim version 8.0. 

``` 
readlink `which vim` 
```

**Comment by hoetmaaiers** [comment]
@ttcremers very sure, this the output: `../Cellar/vim/8.0.0636/bin/vim`

**Comment by dimanyc** [comment]
having this same issue every time I try to edit a commit message

**Comment by risentveber** [comment]
@dimanyc I've solved this by
`git config --global core.editor "vim --noplugin"`
