### ISSUE TITLE
Links to screencasts takes to page with no videos

### ISSUE THREAD

**Issue by sdeleon28** [SirVer/ultisnips#851]
It looks like the pages that used to hold the screencasts are broken.

**Comment by sectioneight** [comment]
It's due to trying to load youtube embeds over HTTP instead of HTTPS:

![image](https://user-images.githubusercontent.com/97087/26953732-fa767484-4c60-11e7-8903-41728aa7da6b.png)

**Comment by sectioneight** [comment]
So you can click on https://www.youtube.com/embed/Zik6u0klD40 from the console and view the screencast, but this should be fixed by the author

**Comment by thehunmonkgroup** [comment]
Just a note that this is still broken, but the error seems to have changed:

```
Mixed Content: The page at 'https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js'. This request has been blocked; the content must be served over HTTPS.
cdn.mathjax.org/mathjax/2.5-latest/MathJax.js:32 WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
replaceScript @ cdn.mathjax.org/mathjax/2.5-latest/MathJax.js:32
(anonymous) @ cdn.mathjax.org/mathjax/2.5-latest/MathJax.js:37
(anonymous) @ cdn.mathjax.org/mathjax/2.5-latest/MathJax.js:53
www.sirver.net/:705 Mixed Content: The page at 'https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/' was loaded over HTTPS, but requested an insecure script 'http://sirverscastle.disqus.com/embed.js'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ (index):705
(anonymous) @ (index):706
disqus_comment_count.js:6 Mixed Content: The page at 'https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/' was loaded over HTTPS, but requested an insecure script 'http://sirverscastle.disqus.com/count.js'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ disqus_comment_count.js:6
(anonymous) @ disqus_comment_count.js:7
3thpart.min.js:124 Mixed Content: The page at 'https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/' was loaded over HTTPS, but requested an insecure script 'http://twitter.com/statuses/user_timeline/SirVerII.json?count=3&callback=jsonp1510206463029'. This request has been blocked; the content must be served over HTTPS.
ajax @ 3thpart.min.js:124
get @ 3thpart.min.js:119
getJSON @ 3thpart.min.js:120
(anonymous) @ fastblog.js:76
each @ 3thpart.min.js:19
each @ 3thpart.min.js:12
(anonymous) @ fastblog.js:61
ready @ 3thpart.min.js:15
u @ 3thpart.min.js:23
(index):544 Mixed Content: The page at 'https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/f_WQxYgK0Pk'. This request has been blocked; the content must be served over HTTPS.
```
